---
apiVersion: apps/v1
kind: Deployment
metadata:
 name:  mydeployment
 namespace: default
spec:
 replicas: 1
 selector:
   matchLabels:
    app: mywordpress
 template:
  metadata:
   name: wordpresspod
   labels:
    app: mywordpress
  spec:
    containers:
    - name: wordpress
      image:  wordpress:6.1.1-apache
      ports:
      - containerPort: 80
  
---
apiVersion: v1
kind: Service
metadata:
  name: myservice
  namespace: default
spec:
 type: LoadBalancer
 selector:
   app: mywordpress
 ports:
 - port: 5000
   targetPort: 80