---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
 name:  myreplicaset
 namespace: default
spec:
 replicas: 1
 selector:
   matchLabels:
    app: pythonapp
 template:
  metadata:
   name: pythonapppod
   labels:
    app: pythonapp
  spec:
    containers:
    - name: pythonappcon
      image: python
      ports:
      - containerPort: 5000
  
---
apiVersion: v1
kind: Service
metadata:
  name: pythonsvc
  namespace: default
spec:
 type: NodePort
 selector:
   app: pythonapp
 ports:
 - port: 5000
   targetPort: 5000   