apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: foo-pvc
  namespace: foo
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: foo-pv




---
apiVersion: v1
kind: persistentVolume
metadata:
  name: nfspv
  namespace: newns
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteMany
  nfs:                   # for nfs
   server: 172.31.41.79
   path: /mnt/nfs_share 
# for hostpath
  hostPath:
   path: /mongo