# for spring boot
apiVersion: apps/v1  # kubectl api-resources -o wide 
kind: Deployment
metadata:
  name: springappdeployment
  namespace: newns
spec:
  replicas: 2
  selector:
    matchLabels:
     app: springapp
  template:
    metadata:
      name: springapp
      labels:
        app: springapp
    spec:
      containers:
      - name: springapp
        image: raja9658/spring-boot-mongo:1 
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
         requests:
           memory: 256Mi
           cpu: 400m
         limits:
           memory: 512Mi
           cpu: 500m 
        env:
        - name: MONGO_DB_HOSTNAME
          value: mongosvc
        - name: MONGO_DB_USERNAME
          value: raja
        - name: MONGO_DB_PASSWORD
          value: raja123       
# for springboot service
---
apiVersion: v1
kind: Service
metadata:
  name: myspringservice
  namespace: newns  
spec:
  type: NodePort
  selector:
     app: springapp
  ports:
  - port: 80
    targetPort: 8080

# for database(mongo)
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mongodb
  namespace: newns
spec:
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      name: mongodb
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: raja
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: raja123
        volumeMounts:
        - name: mongodbvol
          mountPath: /data/db
      volumes:    # attach pvc
      - name: mongodbvol
        persistentVolumeClaim: 
          claimName: mongopvc

# create pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongopvc
  namespace: newns
spec:
 accessModes:
 - ReadWriteOnce
 resources:
   requests:
    storage: 1Gi

  
# for mongo service
---
apiVersion: v1
kind: Service
metadata:
  name: mongosvc
  namespace: newns                             
spec:
 type: ClusterIP
 selector:
   app: mongo
 ports:
 - port: 27017
   targetPort: 27017

  
   